apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-orchestration
  namespace: argocd
spec:
  project: argo-cd-setup
  source:
    repoURL: https://github.com/rytswd/get-istio-multicluster.git
    targetRevision: main
    path: clusters/armadillo/argocd/orchestration
    helm:
      valueFiles:
        - without-istio-operator.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

