---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: armadillo-color-svc
spec:
  hosts:
    - color-svc.armadillo-offerings.global
    - color-svc.armadillo-offerings.armadillo
    # - color-svc.bison-offerings.bison.global # Can be anything, as long as appropriate EnvoyFilter is in place on target cluster
  location: MESH_INTERNAL
  exportTo:
    - "*" # Temporarily set this to all namespaces
  ports:
    - name: http-armadillo-color-svc
      number: 8800
      protocol: http
  resolution: DNS
  workloadSelector:
    app.kubernetes.io/name: color-svc-only-blue
