---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: armadillo-color-svc
spec:
  hosts:
    - color-svc.armadillo-offerings.global
    - color-svc.armadillo-offerings.armadillo
  addresses:
    - color-svc.armadillo-offerings.svc.cluster.local
  location: MESH_INTERNAL
  ports:
    - name: http-armadillo-color-svc
      number: 8800
      protocol: http
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: armadillo-color-svc-multicluster-ingress-routing
spec:
  hosts:
    - color-svc.armadillo-offerings.global
    - color-svc.armadillo-offerings.armadillo
  gateways:
    - istio-system/armadillo-multicluster-ingressgateway
  http:
    - match:
        - uri:
            prefix: /chaos
      rewrite:
        uri: /random
      route:
        - destination:
            host: color-svc.armadillo-offerings.svc.cluster.local
            port:
              number: 8800
      fault:
        abort:
          percentage:
            value: 50
          httpStatus: 400

    - match:
        - uri:
            prefix: /armadillo
      rewrite:
        uri: /random
      route:
        - destination:
            host: color-svc.armadillo-offerings.svc.cluster.local
            port:
              number: 8800
