kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # https://github.com/kubernetes-sigs/kind/releases
  - role: control-plane
    image: kindest/node:v1.20.7@sha256:cbeaf907fc78ac97ce7b625e4bf0de16e3ea725daf6b04f930bd14c67c671ff9
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 32011
        hostPort: 32011
        protocol: TCP
      - containerPort: 32021
        hostPort: 32021
        protocol: TCP
      - containerPort: 32031
        hostPort: 32031
        protocol: TCP
kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        authorization-mode: "AlwaysAllow"
