# Armadillo is configured with only bluish colors
---
apiVersion: v1
kind: Service
metadata:
  name: color-svc
  labels:
    app.kubernetes.io/name: color-svc-only-blue
spec:
  ports:
    - name: http
      port: 8800
      targetPort: 8800
  selector:
    app.kubernetes.io/name: color-svc-only-blue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: color-svc-only-blue
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: color-svc-only-blue
        app.kubernetes.io/version: v1
    spec:
      serviceAccountName: color-svc
      containers:
        - image: docker.io/rytswd/color-svc:latest
          name: color-svc
          command:
            - color-svc
          ports:
            - containerPort: 8800
          env:
            - name: ENABLE_DELAY
              value: "true"
            - name: DELAY_DURATION_MILLISECOND
              value: "500"
            - name: ENABLE_CORS
              value: "true"
            - name: DISABLE_RED
              value: "true"
            - name: DISABLE_GREEN
              value: "true"
            - name: DISABLE_BLUE
              value: "false" # The same as default
            - name: DISABLE_YELLOW
              value: "true"
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 30m
              memory: 30Mi
