#!/bin/bash

__tools_dir=$(dirname "$0")/..
__root_dir="$__tools_dir"/..

ARGO_CD_VERSION=v2.0.1

for e in "armadillo" "bison" "dolphin"; do
    echo "Starting Argo CD update, for cluster '$e'..."

    curl -sSL "https://raw.githubusercontent.com/argoproj/argo-cd/$ARGO_CD_VERSION/manifests/install.yaml" \
        >"$__root_dir"/clusters/$e/argocd/installation/argo-cd-install.yaml

    cat >"$__root_dir"/clusters/$e/argocd/installation/README.md <<EOF
# Argo CD Install with K8s

The yaml file in this folder is generated by the following command:

    curl -sSL "https://raw.githubusercontent.com/argoproj/argo-cd/$ARGO_CD_VERSION/manifests/install.yaml" \\
        > ./clusters/$e/argocd/installation/argo-cd-install.yaml

**NOTE**:  
Argo CD version update is managed by script: tools/internal/update-argo-cd-install.sh
EOF

done
