kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # https://github.com/kubernetes-sigs/kind/releases
  - role: control-plane
    image: kindest/node:v1.18.15@sha256:5c1b980c4d0e0e8e7eb9f36f7df525d079a96169c8a8f20d8bd108c0d0889cc4
  - role: worker
    image: kindest/node:v1.18.15@sha256:5c1b980c4d0e0e8e7eb9f36f7df525d079a96169c8a8f20d8bd108c0d0889cc4
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
      # Not sure if this is needed, commenting out for now.
      # - |
      #   kind: ClusterConfiguration
      #   apiServer:
      #     extraArgs:
      #       "service-account-issuer": "kubernetes.default.svc"
      #       "service-account-signing-key-file": "/etc/kubernetes/pki/sa.key"
      #   networking:
      #     dnsDomain: global
    extraPortMappings:
      - containerPort: 32011
        hostPort: 32011
        protocol: TCP
      - containerPort: 32021
        hostPort: 32021
        protocol: TCP
      - containerPort: 32031
        hostPort: 32031
        protocol: TCP
kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        authorization-mode: "AlwaysAllow"
