apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./istio-control-plane-install.yaml
  - ./istio-external-gateways-install.yaml
  - ./istio-multicluster-gateways-install.yaml
  - ./istio-management-gateway-install.yaml

# Remove duplicated resources that are defined in the next canary release.
# Depending on the release, you may need to delete the duplicated resources
# from the newer release instead. In that case, the full installation spec
# should work.
patchesStrategicMerge:
  - ./patches/delete-duplicate-resources-control-plane.yaml
